[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 2000

[theme]
primaryColor = "#1DB954"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
serverAddress = "localhost"
gatherUsageStats = false